#@ load("@ytt:data", "data")
---
kind: ScaledJob
apiVersion: keda.sh/v1alpha1
metadata:
  namespace: keda-example
  name: hangfire-consumer-addition  
spec:
  successfulJobsHistoryLimit: 2
  failedJobsHistoryLimit: 5
  maxReplicaCount: 3  #! Limit the maximum number of kubernetes pods that will be started regardless of queue size
  pollingInterval: 5
  jobTargetRef:    
    parallelism: 1 #! [max number of desired pods](https://kubernetes.io/docs/concepts/workloads/controllers/jobs-run-to-completion/#controlling-parallelism)
    completions: 1 #! [desired number of successfully finished pods](https://kubernetes.io/docs/concepts/workloads/controllers/jobs-run-to-completion/#controlling-parallelism)
    activeDeadlineSeconds: 86400 #! Specifies the duration in seconds relative to the startTime that the job may be active before the system tries to terminate it; value must be positive integer
    #! backoffLimit: 6 # Specifies the number of retries before marking this job failed. Defaults to 6
    template:
      spec:
          containers:
          - name: hangfire-consumer-addition
            image: #@ data.values.container_registry + "/hangfire-consumer:latest"
            env:  
              - name: IdleTimeoutSeconds
                value: "10"
              - name: HangfireQueue
                value: "addition"
              - name: LogLevel
                value: "Information"
              - name: Hangfire__Username
                value: #@ data.values.hangfire_instance_0_username
              - name: Hangfire__Password
                value: #@ data.values.hangfire_instance_0_password
              - name: Hangfire__Address
                value: #@ data.values.sql_server_loadbalancer_ip
              - name: HttpLogEndpoint
                value: #@ data.values.http_log_endpoint
              - name: StartupDelay
                value: "15"
            resources:
              requests:
                memory: "256Mi"
                cpu: "0.01"              
          restartPolicy: OnFailure 

  triggers:
    - type: external
      metadata:
        scalerAddress: keda-externalscaler-hangfire:80
        hangfireInstance: "Example"
        queue: "addition"
        targetSize: "3"  #! Number of hangfire jobs each pod should handle      