HttpLogEndpoint: "http://logstash.devnathan.omniaretail.internal:19500"
MinimumLogLevel: Debug

HangfireInstances:
  - Name: "Example"
    Address: <SQL_SERVER_ADDRESS_HERE>
    Username: <SQL_USERNAME_HERE>
    Password: <SQL_PASSWORD_HERE>
